version: "3.9"

services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: vitae-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env
    volumes:
      - .:/app:delegated
      - /app/node_modules
      - /app/.next
    command: pnpm dev

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: vitae
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
